# Generated by Django 5.0.1 on 2024-04-29 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=4)),
                ("verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email",
                "verbose_name_plural": "Emails",
            },
        ),
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_fullname",
                    models.TextField(max_length=20, verbose_name="Patient Fullname"),
                ),
                ("patient_birthdate", models.DateField(verbose_name="Date of birth")),
                (
                    "patient_phone",
                    models.CharField(max_length=11, verbose_name="Contact"),
                ),
                (
                    "patient_gender",
                    models.TextField(max_length=10, verbose_name="Patient Gender"),
                ),
                (
                    "patient_username",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Username",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Profile",
                "verbose_name_plural": "Patient Profiles",
            },
        ),
    ]
