# Generated by Django 5.0.1 on 2024-05-06 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Clinics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clinic_name",
                    models.CharField(max_length=200, verbose_name="Clinic Name"),
                ),
                ("contacts", models.CharField(max_length=200, verbose_name="Contacts")),
                ("address", models.CharField(max_length=200, verbose_name="Address")),
                (
                    "clinic_location",
                    models.CharField(max_length=200, verbose_name="Clinic Location"),
                ),
            ],
            options={
                "verbose_name": "Clinic",
                "verbose_name_plural": "Clinics",
                "ordering": ["clinic_name"],
            },
        ),
        migrations.CreateModel(
            name="DoctorSpeciality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "speciality_name",
                    models.CharField(max_length=200, verbose_name="Specialty Name"),
                ),
            ],
            options={
                "verbose_name": "Doctor Specialty",
                "verbose_name_plural": "Doctor Specialties",
                "ordering": ["speciality_name"],
            },
        ),
        migrations.CreateModel(
            name="Doctors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doctor_fullname",
                    models.CharField(max_length=200, verbose_name="Full Name"),
                ),
                ("doctor_birthdate", models.DateField(verbose_name="Date of Birth")),
                (
                    "doctor_phone",
                    models.CharField(max_length=11, verbose_name="Contact Phone"),
                ),
                (
                    "doctor_license_no",
                    models.CharField(max_length=200, verbose_name="License Number"),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medcard_app.clinics",
                        verbose_name="Clinic",
                    ),
                ),
                (
                    "doctor_username",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Username",
                    ),
                ),
                (
                    "speciality_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medcard_app.doctorspeciality",
                        verbose_name="Specialty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
                "ordering": ["doctor_fullname", "speciality_name"],
            },
        ),
        migrations.CreateModel(
            name="DoctorReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(verbose_name="Rating of Doctor")),
                ("review", models.CharField(max_length=300, verbose_name="Review")),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medcard_app.doctors",
                        verbose_name="Doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Review",
                "verbose_name_plural": "Doctor Reviews",
                "ordering": ["doctor"],
            },
        ),
        migrations.CreateModel(
            name="DoctorQualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qualification",
                    models.CharField(max_length=300, verbose_name="Qualification"),
                ),
                (
                    "institution",
                    models.CharField(max_length=300, verbose_name="Institution"),
                ),
                ("year_obtained", models.DateField(verbose_name="Year Obtained")),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medcard_app.doctors",
                        verbose_name="Doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Qualification",
                "verbose_name_plural": "Doctor Qualifications",
                "ordering": ["year_obtained"],
            },
        ),
        migrations.CreateModel(
            name="DoctorAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ],
                        verbose_name="Day of the Week",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="medcard_app.doctors",
                        verbose_name="Doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Availability",
                "verbose_name_plural": "Doctor Availabilities",
                "ordering": ["doctor", "day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date of Appointment")),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="scheduled",
                        max_length=100,
                        verbose_name="Status",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Patient",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="medcard_app.doctors",
                        verbose_name="Doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "ordering": ["date", "start_time", "doctor"],
            },
        ),
        migrations.CreateModel(
            name="DoctorWorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place_of_experience",
                    models.CharField(
                        max_length=200, verbose_name="Place of experience"
                    ),
                ),
                ("start_year", models.DateField(verbose_name="Start Date")),
                ("end_year", models.DateField(verbose_name="End Date")),
                (
                    "position",
                    models.CharField(max_length=200, verbose_name="Position Held"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description of Duties"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medcard_app.doctors",
                        verbose_name="Doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Work Experience",
                "verbose_name_plural": "Doctor Work Experiences",
                "ordering": ["-start_year", "-end_year", "doctor"],
            },
        ),
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=4)),
                ("verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email",
                "verbose_name_plural": "Emails",
            },
        ),
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_fullname",
                    models.TextField(max_length=20, verbose_name="Patient Fullname"),
                ),
                ("patient_birthdate", models.DateField(verbose_name="Date of birth")),
                (
                    "patient_phone",
                    models.CharField(max_length=11, verbose_name="Patient Contact"),
                ),
                (
                    "patient_gender",
                    models.TextField(max_length=10, verbose_name="Patient Gender"),
                ),
                (
                    "patient_address",
                    models.CharField(max_length=200, verbose_name="Patient Addresss"),
                ),
                (
                    "patient_username",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Username",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Profile",
                "verbose_name_plural": "Patient Profiles",
            },
        ),
        migrations.AddConstraint(
            model_name="doctoravailability",
            constraint=models.UniqueConstraint(
                fields=("doctor", "day_of_week", "start_time"),
                name="unique_doctor_availability",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.CheckConstraint(
                check=models.Q(("end_time__gt", models.F("start_time"))),
                name="appointment_end_time_must_be_after_start_time",
            ),
        ),
    ]
